# Generated by Django 4.1.5 on 2023-03-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_alter_category_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'products', 'verbose_name_plural': 'products'},
        ),
    ]
